apiVersion: v1
kind: Service
metadata:
  name: jenkins-main
  namespace: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      name: jenkins-main
    - port: 50000
      targetPort: 50000
      name: jenkins-jnlp
  selector:
    app: jenkins-main
